### ISSUE TITLE
数据集和预训练模型

### ISSUE THREAD

**Issue by AI4CT** [syguan96/NeuroFluid#1]
您好！
您的工作很新颖，很有创新，我想复现代码，请问能否上传数据集和预训练模型，谢谢！

**Comment by syguan96** [comment]
您好，谢谢您的夸奖，我刚忙完camera ready，相关模型和数据会在这几天放出来。

**Comment by mengxuyiGit** [comment]
不错的工作！同求数据集和预训练模型，期待尽快release！
请问mesh数据就足够训练，blender的render只是为了visualization对吗？

**Comment by mengxuyiGit** [comment]
nice job！期待尽快见到数据集和预训练模型！
