### ISSUE TITLE
Dataset size

### ISSUE THREAD

**Issue by Boltzmachine** [syguan96/NeuroFluid#14]
Hi I am generating the datasets according to the instruction. I just wonder how much data you generated? 
Also, I found the processes generated by your script are almost the same even if I change the random seed. I wonder if I miss something or not.
Thanks so much!

**Comment by syguan96** [comment]
You should disable `defaul-*` parameters (see parser in `create_physics_scenes.py`).

**Comment by syguan96** [comment]
Also, we have some hard code in `create_physics_scenes.py`, for example in Line 269, we assign density of water with 1000. You can set them random if you need more diverse simulation results.
